# EdgeHunter - Report Module
# Professional pentest report generator

from datetime import datetime
from data.kenya_devices import RISK_LEVELS

class Report:
    def __init__(self):
        self.findings = []
        self.target = ""
        self.start_time = datetime.now()

    def add_finding(self, finding):
        """Add a finding to the report"""
        self.findings.append(finding)

    def calculate_risk_score(self):
        """Calculate overall risk score"""
        if not self.findings:
            return 0

        total = 0
        for finding in self.findings:
            for cve in finding.get("cves", []):
                severity = cve.get("severity", "LOW")
                total += RISK_LEVELS.get(severity, 0)

        return min(100, total)

    def generate_terminal_report(self, target):
        """Generate colored terminal report"""
        self.target = target
        score = self.calculate_risk_score()

        print("\n")
        print("="*60)
        print("   EDGEHUNTER - SECURITY ASSESSMENT REPORT")
        print("="*60)
        print(f"Target:      {target}")
        print(f"Date:        {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        print(f"Findings:    {len(self.findings)}")
        print(f"Risk Score:  {score}/100")

        if score >= 70:
            print(f"Risk Level:  🔴 CRITICAL")
        elif score >= 50:
            print(f"Risk Level:  🟠 HIGH")
        elif score >= 30:
            print(f"Risk Level:  🟡 MEDIUM")
        else:
            print(f"Risk Level:  🟢 LOW")

        print("="*60)

        # Findings
        print("\n📋 FINDINGS:\n")

        for i, finding in enumerate(self.findings, 1):
            print(f"[{i}] {finding.get('name', 'Unknown Device')}")
            print(f"    IP:       {finding.get('ip', 'Unknown')}")
            print(f"    Port:     {finding.get('port', 'Unknown')}")
            print(f"    Org:      {finding.get('org', 'Unknown')}")
            print(f"    City:     {finding.get('city', 'Unknown')}")

            # CVEs
            for cve in finding.get("cves", []):
                severity = cve["severity"]
                if severity == "CRITICAL":
                    icon = "🔴"
                elif severity == "HIGH":
                    icon = "🟠"
                else:
                    icon = "🟡"

                print(f"    {icon} {cve['id']} - {cve['severity']}")
                print(f"       {cve['description']}")

            # Credentials
            if finding.get("credentials_found"):
                creds = finding["credentials_found"]
                print(f"    🔑 Default creds work: {creds['username']}:{creds['password']}")

            print()

        # Recommendations
        print("="*60)
        print("\n💡 RECOMMENDATIONS:\n")
        print("1. Change ALL default credentials immediately")
        print("2. Update firmware on all edge devices")
        print("3. Implement network segmentation")
        print("4. Enable firewall on all edge devices")
        print("5. Disable unnecessary services (Telnet, HTTP)")
        print("6. Implement centralized logging")
        print("7. Regular security assessments")

        print("\n" + "="*60)
        print("Generated by EdgeHunter by Onserio")
        print("For authorized security testing only")
        print("="*60)

    def save_report(self, filename=None):
        """Save report to text file"""
        if not filename:
            filename = f"edgehunter_report_{datetime.now().strftime('%Y%m%d_%H%M')}.txt"

        with open(filename, "w") as f:
            f.write("EDGEHUNTER SECURITY REPORT\n")
            f.write("="*60 + "\n")
            f.write(f"Target: {self.target}\n")
            f.write(f"Date: {datetime.now()}\n")
            f.write(f"Total Findings: {len(self.findings)}\n")
            f.write(f"Risk Score: {self.calculate_risk_score()}/100\n")
            f.write("="*60 + "\n\n")

            for i, finding in enumerate(self.findings, 1):
                f.write(f"[{i}] {finding.get('name', 'Unknown')}\n")
                f.write(f"    IP: {finding.get('ip')}\n")
                f.write(f"    Org: {finding.get('org')}\n")
                for cve in finding.get("cves", []):
                    f.write(f"    CVE: {cve['id']} - {cve['severity']}\n")
                f.write("\n")

        print(f"\n[+] Report saved to {filename}")
        return filename